  steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/my-project-amir-387708/nodejs-calculator", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/my-project-amir-387708/nodejs-calculator"]
  - name: "node:14"
    entrypoint: "npm"
    args: ["install"]
  - name: "node:14"
    entrypoint: "npm"
    args: ["test"]
images:
  - "gcr.io/my-project-amir-387708/nodejs-calculator"
